FROM php:8.2-fpm-alpine




ARG APP_NAME
ARG APP_ENV
ARG APP_KEY
ARG APP_DEBUG
ARG APP_TIMEZONE
ARG APP_URL
ARG APP_LOCALE
ARG APP_FALLBACK_LOCALE
ARG APP_FAKER_LOCALE
ARG APP_MAINTENANCE_DRIVER
ARG PHP_CLI_SERVER_WORKERS
ARG BCRYPT_ROUNDS
ARG LOG_CHANNEL
ARG LOG_STACK
ARG LOG_DEPRECATIONS_CHANNEL
ARG LOG_LEVEL
ARG SESSION_DRIVER
ARG SESSION_LIFETIME
ARG SESSION_ENCRYPT
ARG SESSION_PATH
ARG SESSION_DOMAIN
ARG BROADCAST_CONNECTION
ARG FILESYSTEM_DISK
ARG QUEUE_CONNECTION
ARG CACHE_STORE
ARG CACHE_PREFIX
ARG MEMCACHED_HOST
ARG REDIS_CLIENT
ARG REDIS_HOST
ARG REDIS_PASSWORD
ARG REDIS_PORT
ARG MAIL_MAILER
ARG MAIL_SCHEME
ARG MAIL_HOST
ARG MAIL_PORT
ARG MAIL_USERNAME
ARG MAIL_PASSWORD
ARG MAIL_FROM_ADDRESS
ARG MAIL_FROM_NAME
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_DEFAULT_REGION
ARG AWS_BUCKET
ARG AWS_USE_PATH_STYLE_ENDPOINT
ARG VITE_APP_NAME



ENV APP_NAME=$APP_NAME
ENV APP_ENV=$APP_ENV
ENV APP_KEY=$APP_KEY
ENV APP_DEBUG=$APP_DEBUG
ENV APP_TIMEZONE=$APP_TIMEZONE
ENV APP_URL=$APP_URL
ENV APP_LOCALE=$APP_LOCALE
ENV APP_FALLBACK_LOCALE=$APP_FALLBACK_LOCALE
ENV APP_FAKER_LOCALE=$APP_FAKER_LOCALE
ENV APP_MAINTENANCE_DRIVER=$APP_MAINTENANCE_DRIVER
ENV PHP_CLI_SERVER_WORKERS=$PHP_CLI_SERVER_WORKERS
ENV BCRYPT_ROUNDS=$BCRYPT_ROUNDS
ENV LOG_CHANNEL=$LOG_CHANNEL
ENV LOG_STACK=$LOG_STACK
ENV LOG_DEPRECATIONS_CHANNEL=$LOG_DEPRECATIONS_CHANNEL
ENV LOG_LEVEL=$LOG_LEVEL
ENV SESSION_DRIVER=$SESSION_DRIVER
ENV SESSION_LIFETIME=$SESSION_LIFETIME
ENV SESSION_ENCRYPT=$SESSION_ENCRYPT
ENV SESSION_PATH=$SESSION_PATH
ENV SESSION_DOMAIN=$SESSION_DOMAIN
ENV BROADCAST_CONNECTION=$BROADCAST_CONNECTION
ENV FILESYSTEM_DISK=$FILESYSTEM_DISK
ENV QUEUE_CONNECTION=$QUEUE_CONNECTION
ENV CACHE_STORE=$CACHE_STORE
ENV CACHE_PREFIX=$CACHE_PREFIX
ENV MEMCACHED_HOST=$MEMCACHED_HOST
ENV REDIS_CLIENT=$REDIS_CLIENT
ENV REDIS_HOST=$REDIS_HOST
ENV REDIS_PASSWORD=$REDIS_PASSWORD
ENV REDIS_PORT=$REDIS_PORT
ENV MAIL_MAILER=$MAIL_MAILER
ENV MAIL_SCHEME=$MAIL_SCHEME
ENV MAIL_HOST=$MAIL_HOST
ENV MAIL_PORT=$MAIL_PORT
ENV MAIL_USERNAME=$MAIL_USERNAME
ENV MAIL_PASSWORD=$MAIL_PASSWORD
ENV MAIL_FROM_ADDRESS=$MAIL_FROM_ADDRESS
ENV MAIL_FROM_NAME=$MAIL_FROM_NAME
ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
ENV AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
ENV AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
ENV AWS_BUCKET=$AWS_BUCKET
ENV AWS_USE_PATH_STYLE_ENDPOINT=$AWS_USE_PATH_STYLE_ENDPOINT
ENV VITE_APP_NAME=$VITE_APP_NAME





# Set working directory
WORKDIR /var/www/html

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Update package list and install dependencies
RUN apk update && apk add --no-cache \
    bash \
    postgresql-dev \
    postgresql-libs \
    nodejs \
    npm \
    mysql-client \
    libpng-dev \
    libjpeg-turbo-dev \
    freetype-dev

# Install Yarn
RUN npm install -g yarn

# Install PHP extensions
RUN docker-php-ext-install pdo pdo_pgsql pdo_mysql

# Copy application files
COPY . /var/www/html




# APP_NAME=Laravel
# APP_ENV=local
# APP_KEY=base64:Q48lX7nAVEY8FnU/cADej+arxORxtcsIqGIl5PaZYJ4=
# APP_DEBUG=true
# APP_TIMEZONE=UTC
# APP_URL=http://localhost
# APP_LOCALE=en
# APP_FALLBACK_LOCALE=en
# APP_FAKER_LOCALE=en_US
# APP_MAINTENANCE_DRIVER=file
# # APP_MAINTENANCE_STORE=database
# PHP_CLI_SERVER_WORKERS=4
# BCRYPT_ROUNDS=12
# LOG_CHANNEL=stack
# LOG_STACK=single
# LOG_DEPRECATIONS_CHANNEL=null
# LOG_LEVEL=debug
# #DB_CONNECTION=mysql
# #DB_HOST=db
# #DB_PORT=3306
# #DB_DATABASE=laravel_db
# #DB_USERNAME=laravel_user
# #DB_PASSWORD=secret
# SESSION_DRIVER=database
# SESSION_LIFETIME=120
# SESSION_ENCRYPT=false
# SESSION_PATH=/
# SESSION_DOMAIN=null
# BROADCAST_CONNECTION=log
# FILESYSTEM_DISK=local
# QUEUE_CONNECTION=database
# CACHE_STORE=database
# CACHE_PREFIX=
# MEMCACHED_HOST=127.0.0.1
# REDIS_CLIENT=phpredis
# REDIS_HOST=127.0.0.1
# REDIS_PASSWORD=null
# REDIS_PORT=6379
# MAIL_MAILER=log
# MAIL_SCHEME=null
# MAIL_HOST=127.0.0.1
# MAIL_PORT=2525
# MAIL_USERNAME=null
# MAIL_PASSWORD=null
# MAIL_FROM_ADDRESS="hello@example.com"
# MAIL_FROM_NAME="${APP_NAME}"
# AWS_ACCESS_KEY_ID=
# AWS_SECRET_ACCESS_KEY=
# AWS_DEFAULT_REGION=us-east-1
# AWS_BUCKET=
# AWS_USE_PATH_STYLE_ENDPOINT=false
# VITE_APP_NAME="${APP_NAME}"